import type { ThemeConfig } from '../types/stats';

export const FONT_FAMILY_OPTIONS = [
  'Fira Code',
  'Inter',
  'Roboto',
  'Outfit',
  'monospace'
];

export const THEMES: ThemeConfig[] = [
  // --- Popular Themes ---
  {
    id: 'radical',
    name: 'Radical Neon',
    category: 'Popular',
    bg_color: '141321',
    title_color: 'fe428e',
    text_color: 'a9fef7',
    icon_color: 'f8d847',
    border_color: 'fe428e33',
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    category: 'Popular',
    bg_color: '1a1b26',
    title_color: '7aa2f7',
    text_color: 'a9b1d6',
    icon_color: 'bb9af7',
    border_color: '7aa2f733',
  },
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'Popular',
    bg_color: '282a36',
    title_color: 'ff79c6',
    text_color: 'f8f8f2',
    icon_color: 'bd93f9',
    border_color: 'ff79c633',
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    category: 'Popular',
    bg_color: '1e1e2e',
    title_color: 'cba6f7',
    text_color: 'cdd6f4',
    icon_color: '89b4fa',
    border_color: 'cba6f733',
  },
  {
    id: 'monokai',
    name: 'Monokai Pro',
    category: 'Popular',
    bg_color: '2d2a2e',
    title_color: 'ffd866',
    text_color: 'fcfcfa',
    icon_color: 'ff6188',
    border_color: 'ffd86633',
  },
  {
    id: 'one-dark',
    name: 'Atom One Dark',
    category: 'Popular',
    bg_color: '282c34',
    title_color: '61afef',
    text_color: 'abb2bf',
    icon_color: 'e06c75',
    border_color: '61afef33',
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    category: 'Popular',
    bg_color: '191724',
    title_color: 'ebbcba',
    text_color: 'e0def4',
    icon_color: 'c4a7e7',
    border_color: 'ebbcba33',
  },

  // --- Dark Themes ---
  {
    id: 'github-dark',
    name: 'GitHub Dark',
    category: 'Dark',
    bg_color: '0d1117',
    title_color: '58a6ff',
    text_color: 'c9d1d9',
    icon_color: '3fb950',
    border_color: '30363d',
  },
  {
    id: 'nord',
    name: 'Nord Frost',
    category: 'Dark',
    bg_color: '2e3440',
    title_color: '88c0d0',
    text_color: 'e5e9f0',
    icon_color: '81a1c1',
    border_color: '88c0d033',
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'Dark',
    bg_color: '002b36',
    title_color: '268bd2',
    text_color: '839496',
    icon_color: 'b58900',
    border_color: '268bd233',
  },
  {
    id: 'nightowl',
    name: 'Night Owl',
    category: 'Dark',
    bg_color: '011627',
    title_color: 'c792ea',
    text_color: 'd6deeb',
    icon_color: 'ecc48d',
    border_color: 'c792ea33',
  },
  {
    id: 'emerald',
    name: 'Emerald Mint',
    category: 'Dark',
    bg_color: '064e3b',
    title_color: '34d399',
    text_color: 'ecfdf5',
    icon_color: '10b981',
    border_color: '34d39933',
  },
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    category: 'Dark',
    bg_color: '0f091a',
    title_color: 'a855f7',
    text_color: 'e9d5ff',
    icon_color: 'c084fc',
    border_color: 'a855f733',
  },
  {
    id: 'ocean-cyan',
    name: 'Ocean Cyan',
    category: 'Dark',
    bg_color: '0b192c',
    title_color: '1e90ff',
    text_color: 'e0f7fa',
    icon_color: '00e5ff',
    border_color: '1e90ff33',
  },
  {
    id: 'forest-moss',
    name: 'Deep Forest',
    category: 'Dark',
    bg_color: '132a13',
    title_color: '90a955',
    text_color: 'ecf39e',
    icon_color: '31572c',
    border_color: '90a95533',
  },

  // --- Light Themes ---
  {
    id: 'github-light',
    name: 'GitHub Light',
    category: 'Light',
    bg_color: 'ffffff',
    title_color: '0969da',
    text_color: '24292f',
    icon_color: '1a7f37',
    border_color: 'd0d7de',
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    category: 'Light',
    bg_color: 'eff1f5',
    title_color: '8839ef',
    text_color: '4c4f69',
    icon_color: '1e66f5',
    border_color: '8839ef33',
  },
  {
    id: 'solarized-light',
    name: 'Solarized Light',
    category: 'Light',
    bg_color: 'fdf6e3',
    title_color: 'b58900',
    text_color: '657b83',
    icon_color: '268bd2',
    border_color: 'b5890033',
  },
  {
    id: 'tokyonight-light',
    name: 'Tokyo Night Light',
    category: 'Light',
    bg_color: 'e1e2e7',
    title_color: '34548a',
    text_color: '343b58',
    icon_color: '7851a9',
    border_color: '34548a33',
  },
  {
    id: 'rose-pine-dawn',
    name: 'Rosé Pine Dawn',
    category: 'Light',
    bg_color: 'faf4ed',
    title_color: 'd7827e',
    text_color: '575279',
    icon_color: '907aa9',
    border_color: 'd7827e33',
  },
  {
    id: 'pastel-dream',
    name: 'Soft Pastel',
    category: 'Light',
    bg_color: 'f7f0f5',
    title_color: '9b5de5',
    text_color: '4a4e69',
    icon_color: 'f15bb5',
    border_color: '9b5de533',
  },

  // --- Vibrant Themes ---
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    category: 'Vibrant',
    bg_color: '000b1e',
    title_color: '00f0ff',
    text_color: 'ffee00',
    icon_color: 'ff0055',
    border_color: '00f0ff33',
  },
  {
    id: 'synthwave',
    name: 'Synthwave 84',
    category: 'Vibrant',
    bg_color: '2b213a',
    title_color: 'ff7edb',
    text_color: '36f9f6',
    icon_color: 'fe4450',
    border_color: 'ff7edb33',
  },
  {
    id: 'outrun',
    name: 'Outrun Vaporwave',
    category: 'Vibrant',
    bg_color: '0f0e17',
    title_color: 'ff8906',
    text_color: 'fffffe',
    icon_color: 'f25f4c',
    border_color: 'ff890633',
  },
  {
    id: 'shades-of-purple',
    name: 'Shades of Purple',
    category: 'Vibrant',
    bg_color: '2d2b55',
    title_color: 'fad000',
    text_color: 'ffffff',
    icon_color: 'ff628c',
    border_color: 'fad00033',
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    category: 'Vibrant',
    bg_color: '071923',
    title_color: '00f2fe',
    text_color: '4facfe',
    icon_color: '38ef7d',
    border_color: '00f2fe33',
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    category: 'Vibrant',
    bg_color: '1a0c1b',
    title_color: 'ff512f',
    text_color: 'f09819',
    icon_color: 'e100ff',
    border_color: 'ff512f33',
  },
  {
    id: 'blood-moon',
    name: 'Crimson Moon',
    category: 'Vibrant',
    bg_color: '120003',
    title_color: 'ff003c',
    text_color: 'f2a7b3',
    icon_color: 'ff2a00',
    border_color: 'ff003c33',
  },
  {
    id: 'cyber-pink',
    name: 'Neon Cyber Pink',
    category: 'Vibrant',
    bg_color: '120017',
    title_color: 'ff007f',
    text_color: 'e2b0ff',
    icon_color: '00ffff',
    border_color: 'ff007f33',
  },

  // --- Retro & Specialized Themes ---
  {
    id: 'gruvbox',
    name: 'Gruvbox Dark',
    category: 'Retro',
    bg_color: '282828',
    title_color: 'fabd2f',
    text_color: 'ebdbb2',
    icon_color: 'fe8019',
    border_color: 'fabd2f33',
  },
  {
    id: 'matrix',
    name: 'Matrix Code',
    category: 'Retro',
    bg_color: '000000',
    title_color: '00ff66',
    text_color: '00cc44',
    icon_color: '00ff00',
    border_color: '00ff6633',
  },
  {
    id: 'coffee-latte',
    name: 'Espresso Roast',
    category: 'Retro',
    bg_color: '1f1917',
    title_color: 'd4a373',
    text_color: 'faedcd',
    icon_color: 'e9edc9',
    border_color: 'd4a37333',
  },
  {
    id: 'tokyo-arcade',
    name: 'Arcade Neon',
    category: 'Retro',
    bg_color: '050515',
    title_color: 'ff0055',
    text_color: '00ffff',
    icon_color: 'ffcc00',
    border_color: 'ff005533',
  },
];

