import type { ThemeConfig } from '../types/stats';

export const FONT_FAMILY_OPTIONS = [
  'Fira Code',
  'Inter',
  'Roboto',
  'Outfit',
  'monospace'
];

export const THEMES: ThemeConfig[] = [
  {
    id: 'radical',
    name: 'Radical Neon',
    category: 'Popular',
    bg_color: '141321',
    title_color: 'fe428e',
    text_color: 'a9fef7',
    icon_color: 'f8d847',
    border_color: 'fe428e33',
  },
  {
    id: 'tokyonight',
    name: 'Tokyo Night',
    category: 'Popular',
    bg_color: '1a1b26',
    title_color: '7aa2f7',
    text_color: 'a9b1d6',
    icon_color: 'bb9af7',
    border_color: '7aa2f733',
  },
  {
    id: 'dracula',
    name: 'Dracula',
    category: 'Popular',
    bg_color: '282a36',
    title_color: 'ff79c6',
    text_color: 'f8f8f2',
    icon_color: 'bd93f9',
    border_color: 'ff79c633',
  },
  {
    id: 'catppuccin',
    name: 'Catppuccin Mocha',
    category: 'Popular',
    bg_color: '1e1e2e',
    title_color: 'cba6f7',
    text_color: 'cdd6f4',
    icon_color: '89b4fa',
    border_color: 'cba6f733',
  },
  {
    id: 'catppuccin-latte',
    name: 'Catppuccin Latte',
    category: 'Light',
    bg_color: 'eff1f5',
    title_color: '8839ef',
    text_color: '4c4f69',
    icon_color: '1e66f5',
    border_color: '8839ef33',
  },
  {
    id: 'nord',
    name: 'Nord Frost',
    category: 'Dark',
    bg_color: '2e3440',
    title_color: '88c0d0',
    text_color: 'e5e9f0',
    icon_color: '81a1c1',
    border_color: '88c0d033',
  },
  {
    id: 'gruvbox',
    name: 'Gruvbox Dark',
    category: 'Retro',
    bg_color: '282828',
    title_color: 'fabd2f',
    text_color: 'ebdbb2',
    icon_color: 'fe8019',
    border_color: 'fabd2f33',
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    category: 'Vibrant',
    bg_color: '000b1e',
    title_color: '00f0ff',
    text_color: 'ffee00',
    icon_color: 'ff0055',
    border_color: '00f0ff33',
  },
  {
    id: 'monokai',
    name: 'Monokai Pro',
    category: 'Popular',
    bg_color: '2d2a2e',
    title_color: 'ffd866',
    text_color: 'fcfcfa',
    icon_color: 'ff6188',
    border_color: 'ffd86633',
  },
  {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    category: 'Dark',
    bg_color: '002b36',
    title_color: '268bd2',
    text_color: '839496',
    icon_color: 'b58900',
    border_color: '268bd233',
  },
  {
    id: 'synthwave',
    name: 'Synthwave 84',
    category: 'Vibrant',
    bg_color: '2b213a',
    title_color: 'ff7edb',
    text_color: '36f9f6',
    icon_color: 'fe4450',
    border_color: 'ff7edb33',
  },
  {
    id: 'one-dark',
    name: 'Atom One Dark',
    category: 'Popular',
    bg_color: '282c34',
    title_color: '61afef',
    text_color: 'abb2bf',
    icon_color: 'e06c75',
    border_color: '61afef33',
  },
  {
    id: 'nightowl',
    name: 'Night Owl',
    category: 'Dark',
    bg_color: '011627',
    title_color: 'c792ea',
    text_color: 'd6deeb',
    icon_color: 'ecc48d',
    border_color: 'c792ea33',
  },
  {
    id: 'outrun',
    name: 'Outrun Vaporwave',
    category: 'Vibrant',
    bg_color: '0f0e17',
    title_color: 'ff8906',
    text_color: 'fffffe',
    icon_color: 'f25f4c',
    border_color: 'ff890633',
  },
  {
    id: 'rose-pine',
    name: 'Rosé Pine',
    category: 'Popular',
    bg_color: '191724',
    title_color: 'ebbcba',
    text_color: 'e0def4',
    icon_color: 'c4a7e7',
    border_color: 'ebbcba33',
  },
  {
    id: 'shades-of-purple',
    name: 'Shades of Purple',
    category: 'Vibrant',
    bg_color: '2d2b55',
    title_color: 'fad000',
    text_color: 'ffffff',
    icon_color: 'ff628c',
    border_color: 'fad00033',
  },
  {
    id: 'emerald',
    name: 'Emerald Mint',
    category: 'Dark',
    bg_color: '064e3b',
    title_color: '34d399',
    text_color: 'ecfdf5',
    icon_color: '10b981',
    border_color: '34d39933',
  },
  {
    id: 'midnight-purple',
    name: 'Midnight Purple',
    category: 'Dark',
    bg_color: '0f091a',
    title_color: 'a855f7',
    text_color: 'e9d5ff',
    icon_color: 'c084fc',
    border_color: 'a855f733',
  },
];
